version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: power_bi_postgres
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: power_bi_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  telegram-bot:
    image: bi-telegram-bot:latest
    container_name: bi-telegram-bot
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  photo-server:
    image: bi-photo-server:latest
    container_name: bi-photo-server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: power_bi_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
